email: markuslohde23@gmail.com
full_name: Markus Löhde
name: Markus
background: Markus is a 25 year old student currently studying computer science at TUM, Munich. He is in his 2nd semester of his masters and part of the entrepreneurship scholarship Manage&More.
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences: | # Include any important pieces of information like people or adresses or similar here. 
response_preferences: 
timezone: "CET" 
rewrite_preferences: | 
  Markus has a few rules for how he likes his emails to be written:

  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual.
  - Markus will match the language the original email has been written in, e.g. if receiving an email in german, he will answer in german. 
  - If working with an assistant to schedule, then he is usually more formal
  - If conversing with someone he seems to know well, then he is more direct and to the fact
  - Markus REALLY does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Markus
  - When Markus is casual, he generally includes only a short greeting and sign-off.

triage_no: |
  - Automated emails from services that are spamming Markus
  - Cold outreach from vendors - this happens a lot as people try to sell Markus things. He is not interested in these
  - Generally do not need to see emails from Ramp, Rewatch, Stripe
  - Notifications of comments on Google Docs
  - Automated calendar invitations
  - Automated emails, e.g. confirmations of paypal payment or booking confirmation or LinkedIn notifications
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Emails that notify Markus about messages he did not attend to yet (LinkedIn, Teams, Slack)
  - Emails where there is a clear action item from Markus based on a previous conversation, like adding people to a slack channel or setting up a metting
  - Emails that contain relevant organizational information for events, trips or programs Markus is part of. 
triage_email: |
  - Emails from clients that explicitly ask Markus a question
  - Emails from clients where someone else has scheduled a meeting for Markus, and Markus has not already chimed in to express his excitement
  - Emails from clients or potential customers where Markus is the main driver of the conversation
  - Email from clients where they are trying to set up a time to meet
  - Emails where it seems like Markus has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, Markus should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, Markus should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
